# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- pr

variables:
  # Build configuration setting
  buildConfiguration: 'Release'

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '45a6fef4-d860-401b-9ec2-7d6c0101f1f0'

  # Function app name
  functionAppName: 'func-rkh-twittersar-dev'

  # ARM template location
  armTemplateLocation: 'https://raw.githubusercontent.com/lp-code/AzTwitterSAR/master/infrastructure/'

  # Agent VM image name
  vmImageName: vs2017-win2016

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/azTwitterSar'

stages:
- stage: Build
  displayName: Build AzTwitterSAR, release configuration

  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: $(workingDirectory)/*.csproj

    - task: DotNetCoreCLI@2
      displayName: Build step dotnetcore
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --no-restore --configuration $(buildConfiguration)

    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: $(workingDirectory)/*.csproj
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(buildConfiguration)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop

- stage: CreateCloudResources
  displayName: Create cloud resources
  dependsOn: Build

  jobs:
  - job: Create
    displayName: Create
    
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy template'
      inputs:
        ConnectedServiceName: 'ConnectDevopsToAzure_rg-rkh-twittersarvestpd-dev'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'rg-rkh-twittersarvestpd-dev'
        location: 'norwayeast'
        templateLocation: 'URL of the file'
        csmFileLink: '$(armTemplateLocation)aztwittersar_template.json'
        csmParametersFileLink: '$(armTemplateLocation)aztwittersar_parameters.json'
        deploymentMode: 'Complete'
        deploymentName: 'AzTwitterSAR-Pipeline'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: dev
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
